__author__ = 'Swoosh'

#general
OST_SERVER_VERSION = 0x01


#opcodes
OST_OPCODE_MSG_S2C_HANDSHAKE_CHALLENGE = 0x01
OST_OPCODE_MSG_S2C_NEWCLIENT_BROADCAST = 0x03
OST_OPCODE_MSG_S2C_CHAT_MESSAGE = 0x05
OST_OPCODE_MSG_S2C_MEMBER_DISCONNECT = 0x06
OST_OPCODE_MSG_S2C_MEMBER_TYPING = 0x08
OST_OPCODE_MSG_S2C_HANDSHAKE_STATE = 0x0A
OST_OPCODE_MSG_S2C_ONLINE_LIST = 0x09

OST_OPCODE_MSG_C2S_HANDSHAKE_RESPONSE = 0x02
OST_OPCODE_MSG_C2S_CHAT_MESSAGE = 0x04
OST_OPCODE_MSG_C2S_MEMBER_TYPING = 0x07

#handshake shit
OST_AUTH_HANDSHAKE_OKAY = 0x00
OST_AUTH_HANDSHAKE_ERROR = 0x01

